# Generated by Django 4.1.5 on 2023-01-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spicy', models.FloatField()),
                ('sweet', models.FloatField()),
                ('bitter', models.FloatField()),
                ('sour', models.FloatField()),
                ('salty', models.FloatField()),
                ('soup', models.BooleanField()),
            ],
        ),
    ]
