# Generated by Django 4.1.5 on 2023-01-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuRecommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
